// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiHcc.Dato;

#nullable disable

namespace WebApiHcc.Migrations
{
    [DbContext(typeof(HccContexto))]
    [Migration("20240717013531_ApiHcc")]
    partial class ApiHcc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiHcc.Modelo.Almacen", b =>
                {
                    b.Property<int>("alm_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("alm_id"));

                    b.Property<int>("alm_cantidad")
                        .HasColumnType("int");

                    b.Property<byte>("alm_estatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("alm_fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("alm_id");

                    b.ToTable("Tb_HccAlmacen");
                });

            modelBuilder.Entity("WebApiHcc.Modelo.CatEstatusOrden", b =>
                {
                    b.Property<int>("catord_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("catord_id"));

                    b.Property<byte>("catord_estatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("catord_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("catord_id");

                    b.ToTable("Tb_HccCatEstatusOrden");
                });

            modelBuilder.Entity("WebApiHcc.Modelo.Mesa", b =>
                {
                    b.Property<int>("mes_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mes_id"));

                    b.Property<byte>("mes_disponible")
                        .HasColumnType("tinyint");

                    b.Property<byte>("mes_estatus")
                        .HasColumnType("tinyint");

                    b.Property<short>("mes_lugares")
                        .HasColumnType("smallint");

                    b.HasKey("mes_id");

                    b.ToTable("Tb_HccMesas");
                });

            modelBuilder.Entity("WebApiHcc.Modelo.Orden", b =>
                {
                    b.Property<int>("ord_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ord_id"));

                    b.Property<int>("catord_id")
                        .HasColumnType("int");

                    b.Property<int>("mes_id")
                        .HasColumnType("int");

                    b.Property<byte>("ord_estatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("ord_fecha_inicio")
                        .HasColumnType("datetime2");

                    b.HasKey("ord_id");

                    b.ToTable("Tb_HccOrdenes");
                });

            modelBuilder.Entity("WebApiHcc.Modelo.OrdenDetalle", b =>
                {
                    b.Property<int>("orddet_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orddet_id"));

                    b.Property<int>("ord_id")
                        .HasColumnType("int");

                    b.Property<int>("orddet_cantidad")
                        .HasColumnType("int");

                    b.Property<byte>("orddet_estatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("pro_id")
                        .HasColumnType("int");

                    b.HasKey("orddet_id");

                    b.HasIndex("ord_id");

                    b.ToTable("Tb_HccOrdenesDetalle");
                });

            modelBuilder.Entity("WebApiHcc.Modelo.Producto", b =>
                {
                    b.Property<int>("pro_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pro_id"));

                    b.Property<int>("alm_id")
                        .HasColumnType("int");

                    b.Property<string>("pro_descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("pro_estatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("pro_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("pro_precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("pro_id");

                    b.ToTable("Tb_HccProductos");
                });

            modelBuilder.Entity("WebApiHcc.Modelo.OrdenDetalle", b =>
                {
                    b.HasOne("WebApiHcc.Modelo.Orden", "Orden")
                        .WithMany("OrdenesDetalle")
                        .HasForeignKey("ord_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("WebApiHcc.Modelo.Orden", b =>
                {
                    b.Navigation("OrdenesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
